apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: make-exercise-javascript
  annotations:
    github.com/project-slug: integromat/make-exercise-javascript
spec:
  type: library
  lifecycle: internal
  owner: group:default/make-engineering
  partOfCoreProduct: false
